### PR TITLE
[#139] Fix /transactions/addresses endpoint return

### LINKED ISSUE #139: Endpoint /transactions/addresses is not returning existing transactions
On testnet (could be happening on mainnet too), the `/transactions/addresses` endpoint is not returning what it should, leading to wrong behavior in the web wallet.

- https://testnet.lto.network/transactions/info/EFqPrYPQ9hBuv6WvcxThxBVb7vZq7UTAFXFphtHp7HBg
- http://testnet.lto.network/index/transactions/addresses/3N2kmoXi5SS54HrY3STaKGPA9TQ7KVKVMnV?type=anchor

The transaction exists on the chain, but the web wallet doesn't display it because of the wrong return of the endpoint.

~~This potentially has something to do with environment variables. `TRANSACTION_INDEXING` defaulting to `false` *could* mean that  `/transactions/addresses` won't work properly, as it relies on the `nodeService.countTransactionsByAddress()` method.~~

~~If true, the `docker-compose` on the node repositories should be updated to include `TRANSACTION_INDEXING=true`.~~

### PR DESCRIPTION
**Pull request by brunodb3**
- Fixes the issue with `/transactions/addresses` endpoint
  - The indexing was not behaving properly due to an error implementing `AwaitLock`
  - `AwaitLock` was getting stuck when multiple listeners were activated, so the data was never saved to the database
- Fixes/moves `leveldb` connection handling of errors on `.get` method
  - Instead of throwing an error when value is not found, returns an empty list. This was done on the `leveldb.service` previously, but a better place is on the `leveldb.connection`, as it covers more use-cases  
- Some identation and linting fixes

---

closes #139

### CODE REVIEW

**Comment by brunodb3** [comment]
Tested with `redis`, the error only happened with `leveldb`. PR is good to go.

File: src/leveldb/classes/leveldb.connection.ts [hunk 1]
```diff
@@ -26,15 +30,16 @@ export class LeveldbConnection {
   async add(key: level.KeyType, value: string): Promise<string> {
     await this.incrLock.acquireAsync();
 
-    const existing = await this.connection.get(key).catch(() => null);
-
-    if (existing) return existing;
-
-    const result = await this.connection.put(key, value);
+    try {
+      const existing = await this.connection.get(key).catch(() => null);
```
Comment (jasny) [inline src/leveldb/classes/leveldb.connection.ts:34]: Should not catch the error.

**Review by jasny — APPROVED** [review]

File: src/leveldb/classes/leveldb.connection.ts (hunk 1 above)
Comment (brunodb3) [reply src/leveldb/classes/leveldb.connection.ts]: Done

**Review by jasny — APPROVED** [review]
